### ISSUE TITLE
Look into creating monorepo using lerna for package library

### ISSUE THREAD

**Issue by Robert-OP** [DHI-GRAS/react-components#10]
I think this may be the way to go with `monorepo` and `lerna`:
- repo: https://github.com/lerna/lerna
- docs: https://lerna.js.org/
- article: https://medium.com/@harshverma04111989/creating-monorepo-using-lerna-dd431d0db072

**Comment by Robert-OP** [comment]
@bertearazvan 
- let's see if this may be a good way to go with the gras-library
- you can start fresh in a different repo if you want to test it out
- I think we can include storybook with it and cypress tests as well

**Comment by bertearazvan** [comment]
I will give it a try. The Lerna part seems to be the best way to go in regards to both the storybook and the package lib, however, I believe it will require to change all the setup we have so far. 
This article seems helpful for the setup we have right now. https://hackernoon.com/creating-a-library-of-react-components-using-create-react-app-without-ejecting-d182df690c6b

**Comment by bertearazvan** [comment]
I have looked over `lerna` the past days and I have a few thoughts about it.
- It seems like it will require a lot of changes to what we already have on `storybook` and the `CI/CD pipeline` together with the setup (`TravisCI, GitHub packages and npm`) for the package library.
- The folder structure will be a bit odd as we will have both the storybook and the `npm packages` under the same folder packages in the storybook repo.
- As the package name is already used on the `DHI-GRAS/react-components` and as _npm will slowly fade away in front of the GitHub packages_, I believe we would have issues with keeping the same name in the storybook repo. GitHub packages naming works based on the repository name and the organization name.
- `Lerna` works the best with `multiple packages` in a `monorepo` and as we only have one package now, it is not worthy to `migrate to lerna` yet as we will not use it at it's fullest.
- To _solve the redundancy_ in two repositories we can simply have the components living in the package and importing it on the storybook as an npm package.

I will, therefore, close the issue and open it once we will use `lerna`
